# coding: utf-8
from odoo.addons.report_xlsx.report.report_xlsx import ReportXlsx

class PartnerXlsx(ReportXlsx):

    def generate_xlsx_report(self, workbook, data, ps):
        sheet = workbook.add_worksheet("Packing List")
        #################################################################################
        sheet.set_column('A:A', 12)
        sheet.set_column('L:L', 12)
        #################################################################################
        merge_formats = workbook.add_format({'align':'center', 'valign':'vcenter',})
        merge_formats.set_border()
        #################################################################################
        merge_formats_note = workbook.add_format({'align':'left', 'valign':'top',})
        merge_formats_note.set_border()
        #################################################################################
        border_top = workbook.add_format({'align':'left', 'valign':'top',})
        border_top.set_top()
        #################################################################################
        text_header = workbook.add_format({'font_color': '#a6a6a6', 'align':'left', 'valign':'vcenter',})
        text_header.set_font_size('20')
        #################################################################################
        text_title = workbook.add_format({'align':'center', 'valign':'vcenter',})
        text_title.set_font_size('15')
        #################################################################################
        text_center = workbook.add_format({'align':'center', 'valign':'vcenter',})
        #################################################################################
        sheet.write(0, 2, 'PT. LEA SANENT', text_header)  
        sheet.write(0, 28, 'PAGE:')
        sheet.write(1, 15, 'PACKING LIST', text_title)
        sheet.write(2, 22, 'To:')
        sheet.write(3, 0, 'Packing No.')
        sheet.write(3, 1, ':')
        sheet.write(4, 0, 'DO No.')
        sheet.write(4, 1, ':')
        sheet.write(5, 0, 'SO No.')
        sheet.write(5, 1, ':')
        sheet.write(3, 11, 'Packing Date')
        sheet.write(3, 12, ':')
        sheet.write(4, 11, 'DO Date')
        sheet.write(4, 12, ':')
        sheet.write(5, 11, 'SO Date')
        sheet.write(5, 12, ':')
        sheet.merge_range('A8:B9', 'No. Koli', merge_formats)
        sheet.merge_range('C8:D9', 'Weight (Kg)', merge_formats)
        sheet.merge_range('E8:F9', 'Qty Barang per Koli', merge_formats)
        sheet.merge_range('G8:H9', 'Article No.', merge_formats)
        sheet.merge_range('I8:AF8', 'Qty per Size', merge_formats)
        sheet.write(8, 8, 'AL', merge_formats)
        sheet.write(8, 9, 'XS', merge_formats)
        sheet.write(8, 10, 'S', merge_formats)
        sheet.write(8, 11, 'M', merge_formats)
        sheet.write(8, 12, 'L', merge_formats)
        sheet.write(8, 13, 'XL', merge_formats)
        sheet.write(8, 14, 'X', merge_formats)
        sheet.write(8, 15, 'Y', merge_formats)
        sheet.write(8, 16, 'Z', merge_formats)
        sheet.write(8, 17, '25', merge_formats)
        sheet.write(8, 18, '26', merge_formats)
        sheet.write(8, 19, '27', merge_formats)
        sheet.write(8, 20, '28', merge_formats)
        sheet.write(8, 21, '29', merge_formats)
        sheet.write(8, 22, '30', merge_formats)
        sheet.write(8, 23, '31', merge_formats)
        sheet.write(8, 24, '32', merge_formats)
        sheet.write(8, 25, '33', merge_formats)
        sheet.write(8, 26, '34', merge_formats)
        sheet.write(8, 27, '35', merge_formats)
        sheet.write(8, 28, '36', merge_formats)
        sheet.write(8, 29, '38', merge_formats)
        sheet.write(8, 30, '40', merge_formats)
        sheet.write(8, 31, '42', merge_formats)
        sheet.merge_range('AG8:AH9', 'Qty Shipped (Pcs)', merge_formats)
        sheet.merge_range('AI8:AJ9', 'Qty Order (Pcs)', merge_formats)
        sheet.merge_range('A10:B10', '', merge_formats)
        sheet.merge_range('C10:D10', '', merge_formats)
        sheet.merge_range('E10:F10', '', merge_formats)
        sheet.merge_range('G10:H10', '', merge_formats)
        sheet.write('I10', '', merge_formats)
        sheet.write('J10', '', merge_formats)
        sheet.write('K10', '', merge_formats)
        sheet.write('L10', '', merge_formats)
        sheet.write('M10', '', merge_formats)
        sheet.write('N10', '', merge_formats)
        sheet.write('O10', '', merge_formats)
        sheet.write('P10', '', merge_formats)
        sheet.write('Q10', '', merge_formats)
        sheet.write('R10', '', merge_formats)
        sheet.write('S10', '', merge_formats)
        sheet.write('T10', '', merge_formats)
        sheet.write('U10', '', merge_formats)
        sheet.write('V10', '', merge_formats)
        sheet.write('W10', '', merge_formats)
        sheet.write('X10', '', merge_formats)
        sheet.write('Y10', '', merge_formats)
        sheet.write('Z10', '', merge_formats)
        sheet.write('AA10', '', merge_formats)
        sheet.write('AB10', '', merge_formats)
        sheet.write('AC10', '', merge_formats)
        sheet.write('AD10', '', merge_formats)
        sheet.write('AE10', '', merge_formats)
        sheet.write('AF10', '', merge_formats)
        sheet.merge_range('AG10:AH10', '', merge_formats)
        sheet.merge_range('AI10:AJ10', '', merge_formats)
        sheet.merge_range('A12:B13', 'Total Koli', merge_formats)
        sheet.merge_range('D12:E13', 'Total Weight (Kg)', merge_formats)
        sheet.merge_range('G12:H13', 'Total Article', merge_formats)
        sheet.merge_range('J12:K13', 'Total Qty Shipped', merge_formats)
        sheet.merge_range('A14:B14', '', merge_formats)
        sheet.merge_range('D14:E14', '', merge_formats)
        sheet.merge_range('G14:H14', '', merge_formats)
        sheet.merge_range('J14:K14', '', merge_formats)
        sheet.merge_range('M12:AJ14', 'NOTES:', merge_formats_note)
        sheet.write(15, 0, 'Packager ;',)
        sheet.write(15, 6, 'Warehouse Head ;',)
        sheet.write(15, 23, 'Receive Date ;',)
        sheet.write(15, 30, 'Receiver ;',)
        sheet.merge_range('A21:E21', 'name & sign.', border_top)
        sheet.merge_range('G21:K21', 'name & sign.', border_top)
        sheet.merge_range('AE21:AJ21', 'name, sign & company stamp.', border_top)

PartnerXlsx('report.lea.packing.list.xlsx',
            'lea.packing.list')